attempt to fix compilation on non MSYS2 windows by ignoring renaming of the C cgdriv routine and using __stdcall conditioned on presence of _WIN32 flag
On Windows some systems (e.g.,
http://www.cpantesters.org/cpan/report/8873d11c-6bf4-1014-a567-c449e8ac8693
) the linker is attempting to resolve a C routine with a trailing
underscore, but can't find it. Here's the error message:

Failed test 'xs'
at t/xs.t line 17.
  ExtUtils::CBuilder->link failed
    Generating script 'C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.lds'
    dlltool --def "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.def" --output-exp "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.exp"
    g++ -o "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.xs.dll" -Wl,--base-file,"C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.base" -Wl,--image-base,0xc2e0000 -LC:/STRAWB~1/cpan/build/Alien-PGPLOT-v5.2.2.4-0/blib/lib/auto/share/dist/Alien-PGPLOT/lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0 -Lc:/Strawberry282/c/bin/../lib/gcc -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../i686-w64-mingw32/lib/../lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../i686-w64-mingw32/lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../.. -mdll -s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib" -mdll -s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib" "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.lds" -lcpgplot -lpgplot -lm -lgfortran -lmingw32 -lmoldname -lmingwex -lmsvcrt -lquadmath -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -liconv -lpng -lz "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.exp"
    C:/STRAWB~1/cpan/build/Alien-PGPLOT-v5.2.2.4-0/blib/lib/auto/share/dist/Alien-PGPLOT/lib/libpgplot.a(grexec.o): In function `grexec_':
    c:\STRAWB~1\cpan\build\Alien-PGPLOT-v5.2.2.4-0\_alien\build_erZD\pgplot-5.2.2-8\drivers/grexec.f:60: undefined reference to `cgdriv_'
    collect2.exe: error: ld returned 1 exit status
    dlltool --def "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.def" --output-exp "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.exp" --base-file "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.base"
    g++ -o "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.xs.dll" -Wl,--image-base,0xc2e0000 -LC:/STRAWB~1/cpan/build/Alien-PGPLOT-v5.2.2.4-0/blib/lib/auto/share/dist/Alien-PGPLOT/lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0 -Lc:/Strawberry282/c/bin/../lib/gcc -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../i686-w64-mingw32/lib/../lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../../../i686-w64-mingw32/lib -Lc:/Strawberry282/c/bin/../lib/gcc/i686-w64-mingw32/7.1.0/../../.. -mdll -s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib" -mdll -s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib" "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.lds" -lcpgplot -lpgplot -lm -lgfortran -lmingw32 -lmoldname -lmingwex -lmsvcrt -lquadmath -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -liconv -lpng -lz "C:\DOCUME~1\a\LOCALS~1\Temp\test-alien-_MwdvQ\Mod0AAAA.exp"
    C:/STRAWB~1/cpan/build/Alien-PGPLOT-v5.2.2.4-0/blib/lib/auto/share/dist/Alien-PGPLOT/lib/libpgplot.a(grexec.o): In function `grexec_':
    c:\STRAWB~1\cpan\build\Alien-PGPLOT-v5.2.2.4-0\_alien\build_erZD\pgplot-5.2.2-8\drivers/grexec.f:60: undefined reference to `cgdriv_'
    collect2.exe: error: ld returned 1 exit status
Seeded srand with seed '20220705' from local date.